### ISSUE TITLE
Mail notifications show deleted pickups

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1001] opened 2018-04-09 13:49 UTC
Feedback from Nijmegen:
> Last weekend I got an email saying we missed 7 pickups, while I deleted the reccuring pickups more
> than a week ago.. that's buggy, eh?

([Deepld](https://www.deepl.com/translator)) Feedback from EfA:
> Currently, the e-mail notifications also show deleted appointments that are not open or do not exist at all.
>
> For example, some time ago I already deleted some Thursday appointments for picking up the board, as the board will be closed for a few weeks.
>
> Nevertheless, these dates are sent as "still open" / "not yet signet up for" in the e-mail notifications (see below).
>
> 
![image](https://user-images.githubusercontent.com/17573771/38501407-39503090-3c0d-11e8-985b-cfd1ad090d4c.png)

**Comment by oldPadavan** [comment] 2018-06-14 09:55
```
@transaction.atomic
    def delete(self, *args, **kwargs):
        for pickup in self.pickup_dates.\
                filter(date__gte=timezone.now()).\
                annotate(Count('collectors')).\
                filter(collectors__count=0):
            pickup.deleted = True
            pickup.save()
        return super().delete(*args, **kwargs)
```
When PickupDateSeries gets deleted it sets deleted = True at each upcoming PickupDate, but only at those having 0 collectors. Thus if there are already any collectors for the pickup it won't be marked as deleted even though its PickupDateSeries was deleted. It might me the cause of this bug

**Comment by tiltec** [comment] 2018-06-14 19:40
Good find, but the behavior was implemented like this on purpose. My thinking was that pickups shouldn't get deleted in a batch process when people already signed up for it.

I think the problem is somewhere else, because it affects pickups that are already deleted. My guess is that the `pickup.deleted` field is not checked when gathering data for the pickup notification email.

**Comment by oldPadavan** [comment] 2018-06-15 08:31
Thanks for comment @tiltec . Initially I was also thinking about missed `pickup.deleted` somewhere in task code which generates the mails. As I understand 2 types of notifications are mentioned in the bug description: group summary emails for the first case and pickup notifications for the second one. I've checked - both of them contain `deleted=False` in the filters. That's why my idea was that deleted=True wasn't set somewhere on the deletion of PickupSeries.
Also I've found quite similar bug - yunity/karrot-frontend#987, which was closed at the end of March. Current bug was opened at the beginning of April - may be the new code which ignored deleted pickups hasn't been pushed to production by that time and the current bug is actually fixed?

**Comment by tiltec** [comment] 2018-06-15 10:19
> Also I've found quite similar bug - yunity/karrot-frontend#987, which was closed at the end of March. Current bug was opened at the beginning of April - may be the new code which ignored deleted pickups hasn't been pushed to production by that time and the current bug is actually fixed?

Possibly! I'll try it out in dev.karrot.world and close if I can't reproduce.

By the way, here's a discussion about the feature you found above, where a change to the pickups series doesn't get applied to the individual pickup if it has collectors: https://github.com/yunity/karrot-frontend/issues/611
It's not completely clear to me if it would be better to remove this feature or just make it more explicit in the UI.

**Comment by tiltec** [comment] 2018-06-16 16:36
Bug doesn't seem to exist anymore, possibly it's a confusion cause by #611 that needs to be addressed separately.

**Closed by tiltec** 2018-06-16 16:36 UTC
Labels: backend, bug
