### ISSUE TITLE
Fix InvitationForm frontend validation

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#761] opened 2017-11-16 20:17 UTC
This one shows when trying to invite an email adress, that has already been invited (and even accepted maybe..? Because otherwise the adress is shown below, right..? 🤔 )

![image](https://user-images.githubusercontent.com/17573771/32912961-189349d6-cb11-11e7-89b0-21412ce121af.png)

Since it comes from the backend, I first opened an issue there, in which @tiltec said that 

"it's the default from Django REST Framework and I don't know where to change it. Ideally it should never show to the user anyway. The invite form is apparently missing proper front-end validation.

This bit should have prevented it:
https://github.com/yunity/karrot-frontend/blob/9b82efd73e4d7b3397ea615198c11d202cbd6f87/src/components/Group/InvitationsForm.vue#L55-L58"

**Comment by tiltec** [comment] 2017-11-16 20:32
Related #668

**Comment by tiltec** [comment] 2017-11-25 12:48
I can't reproduce the error above. The invitation form is still a bit rough in other ways, maybe it makes sense to polish it generally?

**Comment by tiltec** [comment] 2017-12-26 10:56
I improved the server error message, I guess that should be enough to close this.

**Closed by tiltec** 2017-12-26 10:56 UTC
Labels: bug, needs-more-info
