### ISSUE TITLE
Sign out does not work

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#1261] opened 2019-01-31 14:58 UTC
On Windows 10 x64 with Firefox 64 and no browser add-ons, the logout does not work.
The UI does not change at all when I click on "Sign out". The only thing that happens is that Sentry is notified via `POST https://sentry.io/api/236883/store/?sentry_key=...` and response `200`.

Using Chrome on the same system the logout works, though.

**Comment by tiltec** [comment] 2019-01-31 20:08
Thanks! I couldn't reproduce it unfortunately, it works in Linux (both newest Firefox & Chromium).

I have an idea, it might be triggered by cleaning up firebase registrations: https://sentry.io/share/issue/2905f350b477455da20d31ad4a55ebaa/
All errors happen on Firefox on Windows, so it might be something special about this combination.

It shouldn't prevent logout in the first place, but it's also interesting why it fails with "The operation is insecure."
Stackoverflow tells us that it might happen when violating the same origin policy: https://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate

**Comment by tiltec** [comment] 2019-03-30 11:45
@mr-kojo Can you check if the error still exists?

**Comment by mr-kojo** [comment] 2019-04-01 18:10
Yes it does. See sentry key 6fd3cc6b432b457e8f18e12aa163a900

**Comment by tiltec** [comment] 2019-04-04 16:28
It should be fixed on karrot.world - please leave a comment here if you encounter the bug again.

**Closed by tiltec** 2019-04-04 16:28 UTC
Labels: bug
